version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestgitbearerProject
  gitServerName: srcGithubCtrl_Arti_bearer
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: GithubPackageDebuglog
  gitServerName: srcGithubCtrl_Arti_bearer
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
